[package]
name = "ssd1677"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"

[dependencies.embedded-graphics-core]
optional = true
version = "0.4.0"

[features]
default = ["graphics"]
graphics = ["embedded-graphics-core"]
